### ISSUE TITLE
Incrementing property of laravel throw an error

### ISSUE THREAD

**Issue by andresdevr** [lepikhinb/laravel-fluent#15] opened 2021-09-28 03:31 UTC
Hi, i was testing some models with uuid, so i need to add de `$incrementing` property to false like the [docs](https://laravel.com/docs/8.x/eloquent#primary-keys), that throws an error, i guess is for the public access of the property

```php
class User extends Model
{
     use Fluent;

     /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
     public $incrementing = false;
}
```
when i try to retrieve the model from database  this throw

```bash
    PHP Error:  Call to a member function getName() on null
```

by the way, i love this package

**Comment by hsmfawaz** [comment] 2021-09-28 15:02
duplicate of #14

**Comment by lepikhinb** [comment] 2021-09-28 15:04
Just tagged v0.0.6. Please update the package.

**Closed by lepikhinb** 2021-09-28 15:04 UTC
